<a href="https://colab.research.google.com/github/bharathulaprasad/data-science/blob/master/Matrices_GettingStarted.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
m=np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
m

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
m.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [9]:
from numpy.linalg import inv
a = np.array([[1., 2.], [3., 4.]])
inv(np.matrix(a))

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [12]:
import numpy.linalg
numpy.linalg.det(a)

-2.0000000000000004

In [13]:
numpy.linalg.eigvals(m)

array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16])